name = "durable-obj-auth-test"
type = "javascript"

account_id = ""
workers_dev = true
route = ""
zone_id = ""

[durable_objects]
bindings = [
    { name = "UserService", class_name = "UserService", script_name="./src/services/UserService.mjs" }
]
